language: python
python:
- 3.6
services: mysql
env:
- DJANGO=2.1.3
before_install:
- sudo apt-get install libmysqlclient-dev python3-dev
install:
- pip3 install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: PcFG54ADmiFbT31mtQTc7uoYImTW/GaQCuo7ljbhQaqP+S8cmLuHT8di+j6uzfdNLXQM8RXUsrOGgk4rD97NAfMVq3JzSEB41NxJup4AciILKcrqWdeD3k2GZDI5swsRzckiMBHEq69pg0otCgS7CwScOngE5tx6hmDMp0OAZ5x8bCGKfcQY/qIRnjRJVv8AOAen2tYfQ7UmA4FBWLtG8FcJOCX/QUQ3mQvOyKmt3GDSW/CpqH/XM9FrKcbdEbvkYmiwQjXttK6w1YcvYAJSKfWdwCeXnzFV6ZUC+dxxAiI4mSYZfog1DAnAoTjjOGc0v2NaVM4mmMXqb99id0HYE/SvncgT3hY8w3hna8biuPeG+Aejvtu9PgNsStkhRhjtwSuoTRcjhfCiUNZge+YFhJxB773fdrijZZaDSkV8Am1EfSmwNnh/62jeTcPvOsNF8T9RXvGzZoylqxWpV4aaUOg1ArgIQmfxnGcXjaH1KftnseB9c/ynguD1YbgWDfqJcByBkoWNdmwIA5QBnQM+7ahDou3y0AsTJTOCQbnaE4dPSW7bx6tZZDUo8D+5DNrWQA8G7vnw5kklNEGMY3EKDUtWqgeDpniWBwV5OprrJ6rl+dxDnQyGe7bZA0UtqWDtxO7pUNMd/LPgt+WgiNM1WFlYQN/0k+oi8UGwwK6HXaM=
  app: hostel-data-vis
