language: python

python:
  - 3.6

services: mysql

env:
  - DJANGO=2.1.3

before_install:
  - sudo apt-get install libmysqlclient-dev python3-dev
install:
  - pip3 install -r requirements.txt
script:
  - python manage.py test

