language: python
python:
- 3.6
services: mysql
env:
- DJANGO=2.1.3
before_install:
- sudo apt-get install libmysqlclient-dev python3-dev
install:
- pip3 install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: ZmUtUzxtHCaCLQrI1rjRQXgJeTd+gGFc6xkCAzlk1Q+p0Z5iCYLsNVguPz9caNtGJfb4LpNYf0+g4mRgnm5D/BG56KFKl8bgda4SjyyfI7mQA8dcLVCOxAcAGCyagp9nRZ0QuT7oqw3Hh3X3F+9QMwUJbMskida4AUSq51X9D+0lsGeP0cuofzaABwdU6hTIDP0B1WVtBZY65B52QqRvMR6r6H3EdsbCJZmNp8vRL1g30xIRgrh1qFIA/06AjwEniyXzOb1vaoRF5MpDJD//HoGVydIdNqEZcse9NZqGcEcpEgwDVundpxB59qYlutpSRsKlmYGIqeqjSTsK7K80iCMy5BCFV/DNcDPylKXIL2zs7tWboGDyv84Zv3tFhjK0sbaE2zz1s8BYx9h3mMrN0opEIgfX5N+E2BKLh2qye54XBPNADE2JE1LiTmUc1vIYDakzVBcNXWOFevZ0hYO8B5KKYMg26wL/YqAqSjWzuXMO6mIw1NHj52nACKn8YCo9qg+s1Z97kKrh8g+NFMIWqKE0x3sq4ngRjPqcuMwPE9eAgDjBS8nwZ2G7/p4p5uFwYGiE2KFqw0i4BJTSYwfrCHDHcvHWqr13WEaf09ZIo5hN4vBec5dqVve7qLH28PcW4UokaALsnuGnkhtlhuZSSE0CUqBSmNbEf+I7Me71pmg=
  app: hostel-data-vis
