language: python
python:
- 3.6
services: mysql
env:
- DJANGO=2.1.3
before_install:
- sudo apt-get install libmysqlclient-dev python3-dev
install:
- pip3 install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: AgbqVME686e9qnqJg8h/ki3DMxsFRDpCoo8pet+WfLzAFrZrtl5CE1TvIBpbnjkAb4OLFUWByaWra6c2Feu8vh2jfLMQ0amQp3PRCkQ2RUaZJAiD6EINEDPcpHP0wGXtY6Uf+emwER3xHZC4ovKZASVfbaFdl3jBJxp58GjaloRHojifquJhr02W4+kWBaqUjmdhkqs2dUPmsK1hNqAU+W87OaIumjU5/cqfrsFHimYLGT6N7Z/+QlQu+GoIbK44pBneYxJWkSekteho/D9gz4Bm8AS+mey6eY/3eQLYHd9pPTqfPrsevFm7IW3xd0pe+mvwlV6byJIjLWlXn7+tcslLbWD8iN1RJTo4LApRKk9ws/vYwYHdRftGu3G8AiJU79EpCoVE3Ll3yjL0JD/MBW536w9YVMuHKNkFENMTVwoQxHWHQrVh8pRtgnGW+tDkjqxEUyLUhoiDAYnLCTZNrWNq6/NxJyt1gn+2Y5vxBMec24gDorc6lAZomPTNxpCau4laTeIofuvqpvy+QrEb/a2CtnMdlZJSep0gGsulQXYwoJaIYVOcM9h+DGm1mE43sI4B92Itg6qBX6qYLda3psGxyexMBDuJv/GLtI5WU7l+xCAUDJUtins+m5rQIWq6Fm8Pg645Y3rL43zMuTyy59E9y15N3X4Bg4gDrHIKX2g=
  app: hostel-data-vis
