version: '3'
services:
  db:
    image: mdillon/postgis
    volumes:
      - ./postgres-data:/var/lib/postgrsql/data
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
  web:
    build: .
    restart: always
    command: bash -c "python3 manage.py makemigrations hostels && python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn project.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgis://postgres:password@db:5432/postgres
