version: '3'
services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: "password"
  web:
    build: .
    command: bash -c "python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgis://postgres:password@db:5432/postgres
