version: 2
jobs:
  style-python:
    docker:
    - image: python
    - image: mdillon/postgis
    working_directory: ~/project
    steps:
    - checkout
    - run: |
        apt-get update &&
        apt-get install pylint -y
    - run: |
        pylint **/*.py

  style-javascript:
    docker:
    - image: python
    - image: mdillon/postgis
    working_directory: ~/project
    steps:
    - checkout
    - run: |
        apt-get update &&
        apt-get install nodejs npm -y &&
        npm install --prefix frontend/ &&
        npm run build --prefix frontend/

  test-python:
    docker:
      - image: python
      - image: mdillon/postgis
    working_directory: ~/project
    steps:
      - checkout
      - run: |
          apt-get update &&
          apt-get install binutils libproj-dev gdal-bin -y &&
      - run: |
          pip install -r requirements.txt &&
          coverage run --source='.' manage.py test the-app-you-want-to-test

  test-javascript:
    docker:
    - image: python
    - image: mdillon/postgis
    working_directory: ~/project
    steps:
    - checkout
    - run: |
        apt-get update &&
        apt-get install nodejs npm -y &&
        npm install --prefix frontend/ &&
        npm run build --prefix frontend/
    -run: echo "Run Tests"

  deploy:
    docker:
      - image: python
      - image: mdillon/postgis
    working_directory: /tmp/project
    steps:
      - checkout
      - run: npm run build
      - run: python manage.py startserver

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - style-python
      - style-javascript
      - test-python:
          requires:
            - style-python
      - test-javascript:
          requires:
          - style-javascript
      - deploy:
          requires:
            - test-python
            - test-javascript
          filters:
              branches:
                  only: master