version: 2
jobs:
  build:
    docker:
      - image: python
      - image: postgres
    working_directory: ~/project

    steps:
      - checkout
      - run: |
          apt update &&
          apt install nodejs npm -y &&
          npm install --prefix client/ &&
          npm run build --prefix client/
      - run: |
          pip install -r server/requirements.txt &&
          python server/manage.py

  deploy-stage:
    docker:
      - image: python:3.7.2
      - image: postgres
    working_directory: /tmp/project
    steps:
      - checkout
      - run: npm run build
      - run: python manage.py startserver

  deploy-prod:
    docker:
      - image: python:3.7.2
      - image: postgres
    working_directory: /tmp/project
    steps:
      - checkout
      - run: npm run build
      - run: python manage.py startserver
