version: 2
jobs:
  test-python:
    docker:
      - image: python
      - image: mdillon/postgis
    working_directory: ~/project
    steps:
      - checkout
      - run: |
          apt-get update &&
          apt-get install nodejs npm binutils libproj-dev gdal-bin -y &&
          npm install --prefix frontend/ &&
          npm run build --prefix frontend/
      - run: |
          pip install -r requirements.txt &&
          python3 manage.py runserver

  test-javascript:
    docker:
    - image: python
    - image: mdillon/postgis
    working_directory: ~/project
    steps:
    - checkout
    - run: |
        apt-get update &&
        apt-get install nodejs npm binutils libproj-dev gdal-bin -y &&
        npm install --prefix frontend/ &&
        npm run build --prefix frontend/
    - run: |
        pip install -r requirements.txt &&
        python3 manage.py runserver

  deploy:
    docker:
      - image: python
      - image: mdillon/postgis
    working_directory: /tmp/project
    steps:
      - checkout
      - run: npm run build
      - run: python manage.py startserver

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - style-python
      - style-javascript
      - test-python:
          requires:
            - style-python
      - test-javascript:
          requires:
          - style-javascript
      - deploy:
          requires:
            - test-python
            - test-javascript
          filters:
              branches:
                  only: master