version: 2
jobs:
  build:
    docker:
      - image: python
      - image: postgres
    working_directory: ~/project

    steps:
      - checkout
      - run: |
          apt update &&
          apt install npm -y &&
          npm run build
      - run: python manage.py

  deploy-stage:
    docker:
      - image: python:3.7.2
      - image: postgres
    working_directory: /tmp/project
    steps:
      - checkout
      - run: npm run build
      - run: python manage.py startserver

  deploy-prod:
    docker:
      - image: python:3.7.2
      - image: postgres
    working_directory: /tmp/project
    steps:
      - checkout
      - run: npm run build
      - run: python manage.py startserver
