version: 2
jobs:
  build:
    docker:
      - image: python
      - image: mdillon/postgis
    working_directory: ~/project

    steps:
      - checkout
      - run: |
          apt-get update &&
          apt-get install nodejs npm libgdal-dev -y &&
          npm install --prefix frontend/ &&
          npm run build --prefix frontend/
      - run: |
          pip install -r requirements.txt &&
          python3 manage.py runserver

  deploy-stage:
    docker:
      - image: python:3.7.2
      - image: mdillon/postgis
    working_directory: /tmp/project
    steps:
      - checkout
      - run: npm run build
      - run: python manage.py startserver

  deploy-prod:
    docker:
      - image: python:3.7.2
      - image: mdillon/postgis
    working_directory: /tmp/project
    steps:
      - checkout
      - run: npm run build
      - run: python manage.py startserver
