# Generated by Django 2.1.3 on 2019-02-28 20:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('description', models.TextField(blank=True, null=True)),
                ('facilities', models.ManyToManyField(to='backend.hostels.Facilities')),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('hostel', models.ForeignKey(db_column='hostel', on_delete=django.db.models.deletion.CASCADE, to='backend.hostels.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='RatingCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingsHostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('hostel', models.ForeignKey(db_column='hostel', on_delete=django.db.models.deletion.CASCADE, to='backend.hostels.Hostel')),
                ('rating_category', models.ForeignKey(blank=True, db_column='rating_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.hostels.RatingCategories')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hostel', models.ForeignKey(db_column='hostel', on_delete=django.db.models.deletion.CASCADE, to='backend.hostels.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='prices',
            name='room_size',
            field=models.ForeignKey(db_column='room_size', on_delete=django.db.models.deletion.CASCADE, to='backend.hostels.RoomSizes'),
        ),
        migrations.AddField(
            model_name='prices',
            name='room_type',
            field=models.ForeignKey(db_column='room_type', on_delete=django.db.models.deletion.CASCADE, to='backend.hostels.RoomTypes'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='policies',
            field=models.ManyToManyField(to='backend.hostels.Policies'),
        ),
    ]
